### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by davebonds** [agentevolution/ae-profiles#1]
- [ ] Add random option to widget
- [ ] Output phone numbers as a href=tel:
- [ ] Add field for country code to output in the above
- [ ] Responsive archive page fix
